
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atguigudb
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  redis:
    host: 192.168.1.150
    password: 123456
    connect-timeout: 60000
    lettuce:
      pool:
        max-active: 2000
    cluster:
      nodes: 192.168.1.150:6379,192.168.1.150:6380,192.168.1.150:6381
  security:
    user:
      password: 12346
      name: admin
  boot:
    admin:
      client:
        url: http://192.168.1.1:8081
# 配置mybatis规则
mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: batch
server:
  port: 8080
  servlet:
    context-path: /hzh
rocketmq:
  name-server: 192.168.1.150:9876;
  producer:
    group: rocketmq1
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"



